### ISSUE TITLE
Protecting Master from accidental pushed

### ISSUE THREAD

**Issue by Nandob777** [umdevclub/umdevclub.github.io#32]
I almost accidently pushed to master in the umdevclub fork instead of my own fork.  Personally I would like a safeguard that stops me or anyone from doing this in the future

**Comment by ratstache** [comment]
This is part of #3 as well. I've been putting it off for a while but I'll get it back on my to-do list. Exec of dev-ops indeed 🥇

**Comment by Nandob777** [comment]
You actually got on it really fast, after the issue was posted, great job.  I think we can close it

**Comment by ratstache** [comment]
This repo will be further protected moving forward. I need to dig out some time to set up the collab processes. Closing for now.
