### ISSUE TITLE
Wiki for resources

### ISSUE THREAD

**Issue by Wynand** [umdevclub/umdevclub.github.io#36]
If we transition to jekyll (#15) or anything complex we need a wiki to help new devs learn how to contribute.

This would also be a better place for the accessibility links from #4 as well as other design directions

**Comment by ratstache** [comment]
Yeah, we can add a section to the wiki to cover this and reference it in the developer setup part.

**Comment by ratstache** [comment]
Closing this issue because it's a duplicate of #3 and we are no longer incorporating jekyll
